services:
  videogameslibraryapi:
    image: videogameslibraryapi
    build:
      context: .
      dockerfile: VideoGamesLibrary.Api/Dockerfile
    container_name: videogameslibrary
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "6400:8080"
      - "6401:8081"